ignoreErrors = ["dnb-sample-error"]

[dnb.debug]
loglink = "https://dnbql.netlify.app/log"
namespace = "dnb"
debuglevel = 8
development = true

[dnb.debug.plugins]
scss = [
  "scss/_debugprint.scss"
]

# formatters setup
# TODO this will move into the data directory as soon as some issues
# with availability in partials are fixed
[[dnb.debug.formatters]]
type = "bool"
class = "flat"
slug = "bool"
label = "Boolean"
description = ""

# todo distinct between integers and floats
[[dnb.debug.formatters]]
catch = "^(int64|float64)$"
class = "flat"
slug = "number"
label = "Number"
description = ""

[[dnb.debug.formatters]]
type = "int"
class = "flat"
slug = "int"
label = "Integer"
description = "a positive or negative number without a floating point"

[[dnb.debug.formatters]]
catch = "^(string|template\\.(CSS|HTML|HTMLAttr|JS|JSStr|URL))$"
class = "flat"
slug = "string"
label = "String"
description = ""

[[dnb.debug.formatters]]
type = "*page.Pager"
class = "struct"
slug = "pager"
label = "Pagination Object"
description = "an object containing pagination information for the current page"

[[dnb.debug.formatters]]
type = "text.Position"
class = "struct"
slug = "position"
label = "Position Object"
description = "an object containing position information for the current line in a shortcode"

[[dnb.debug.formatters]]
type = "time.Time"
class = "flat"
slug = "time"
label = "Time"
description = ""

[[dnb.debug.formatters]]
catch = "^([[][]]|.*TaxonomyList|output\\.Formats|resource\\.Resources|.*navigation\\.Menu$|\\*?hugolib\\.Pages$|hugolib\\.OrderedTaxonomy$|hugolib\\.WeightedPages)"
class = "struct"
slug = "slice"
internal = "map"
label = "Slice"
description = ""

[[dnb.debug.formatters]]
catch = "^(map[[].+[]]|.*SiteSocial|.*navigation\\.Menus$|hugolib\\.AuthorList|hugolib\\.Taxonomy|maps\\.Params)"
class = "struct"
internal = "map"
slug = "map"
label = "Map"
description = ""
weight = 100

[[dnb.debug.formatters]]
type = "*hugolib.ShortcodeWithPage"
class = "struct"
slug = "shortcode"
label = "Shortcode"
description = ""

[[dnb.debug.formatters]]
type = "*hugolib.SiteInfo"
class = "struct"
slug = "siteinfo"
label = "Siteinfo"
description = ""

[[dnb.debug.formatters]]
catch = "^.*gitmap\\.GitInfo"
class = "struct"
slug = "gitinfo"
label = "GitInfo"
description = ""

[[dnb.debug.formatters]]
type = "output.Format"
class = "struct"
slug = "outputformat"
label = "Outputformat"
description = ""

[[dnb.debug.formatters]]
catch = "^\\*resource"
class = "struct"
slug = "resource"
label = "Resource"
description = ""

[[dnb.debug.formatters]]
catch = "^(\\*hugolib\\.Page|.*hugolib\\.pageState)"
class = "struct"
slug = "page"
label = "Page"
description = ""

[[dnb.debug.formatters]]
catch = "^\\*(hugolib|source)\\.[fF]ileInfo$"
class = "struct"
slug = "fileinfo"
label = "FileInfo"
description = ""

[[dnb.debug.formatters]]
catch = "navigation\\.MenuEntry$"
class = "struct"
slug = "menuentry"
label = "Menu Entry"
description = ""

[[dnb.debug.formatters]]
type = "hugolib.OrderedTaxonomyEntry"
class = "struct"
slug = "orderedtaxonomyentry"
label = "Ordered Taxonomy Entry"
description = ""

[[dnb.debug.formatters]]
type = "hugolib.WeightedPage"
class = "struct"
slug = "weightedpage"
label = "Weighted Page"
description = ""
