baseURL = "https://dnb-org.github.io/debug/"

# disabling unused features
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

[[module.imports]]
path = "github.com/dnb-org/dnb-hugo-debug"

[[module.imports]]
path = "github.com/dnb-org/dnb-hugo-hooks"
