# disabling unused features
disableKinds = [
  "taxonomy",
  "taxonomyTerm",
  "RSS",
  "sitemap",
  "robotsTXT"
]



[[module.imports]]
path = "github.com/dnb-org/debug"

[[module.imports]]
path = "github.com/dnb-org/hooks"
